apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    notifications.argoproj.io/subscribe.on-sync-running-statuspage.statuspage: statuspage
    notifications.argoproj.io/statuspage-component-ids: "85fhtdzpxv23"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: docker.io/library/httpd:v0.0.0
          name: guestbook-ui
          ports:
            - containerPort: 80
